name: doctor_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Navegación
  go_router: ^14.0.0

  # Estado
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Serialización
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

  # Base de datos
  sqflite: ^2.4.0
  sqflite_common_ffi: ^2.3.0

  # Persistencia
  shared_preferences: ^2.3.2

  # Gráficos
  fl_chart: ^0.69.0

  # Utilidades
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

  # PDFs
  pdf: ^3.11.1
  printing: ^5.13.2

  # Archivos
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  path: ^1.9.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Generación de código
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  riverpod_generator: ^2.4.3

flutter:
  uses-material-design: true
